### ISSUE TITLE
Linking errors running Python scripts from Darwin binary

### ISSUE THREAD

**Issue by baagaard** [geodynamics/pylith#17]
```
$ python
Python 2.7.10 (default, Jul 14 2015, 19:46:27)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import h5py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Volumes/Tools/unix/pylith-dev/releases/v2.1.2/pylith-2.1.2-darwin-10.10.5/lib/python2.7/site-packages/h5py/__init__.py", line 10, in <module>
    from h5py import _errors
ImportError: dlopen(/Volumes/Tools/unix/pylith-dev/releases/v2.1.2/pylith-2.1.2-darwin-10.10.5/lib/python2.7/site-packages/h5py/_errors.so, 2): Library not loaded: @executable_path/../lib/libmpi.12.dylib
  Referenced from: /Volumes/Tools/unix/pylith-dev/releases/v2.1.2/pylith-2.1.2-darwin-10.10.5/lib/python2.7/site-packages/h5py/_errors.so
  Reason: image not found
```

The workaround is to run the script via `nemesis SCRIPT` or replace `#!/usr/bin/env python` with `#!/usr/bin/env nemesis`.

**Comment by baagaard** [comment]
Fixed in baagaard/fix-examples-pyscript-linking, commit  ef13e2f4b3628d9659459861dbacb85209a4032c.
