### ISSUE TITLE
Fatal error. Calling MPI_Abort() to abort PyLith application (version: pylith 4.0.0,  examples:/box-3d)

### ISSUE THREAD

**Issue by sheyu921** [geodynamics/pylith#680]
## Describe the issue

When I replace the mesh_tet.msh to mesh_tet.exo and run the script step01_axialdisp.cfg, the error shows as below:
(before run the script, the pylith.meshio.MeshIOPetsc has been replaced by pylith.meshio.MeshIOCubit.)
"""
 >> /home/syw/pylith/pylith-4/lib/python3.10/site-packages/pylith/problems/Problem.py:185:initialize
 -- timedependent(info)
 -- Initializing timedependent problem with quasistatic formulation.
Fatal error. Calling MPI_Abort() to abort PyLith application.
Traceback (most recent call last):
  File "/home/syw/pylith/pylith-4/lib/python3.10/site-packages/pylith/apps/PetscApplication.py", line 55, in onComputeNodes
    self.main(*args, **kwds)
  File "/home/syw/pylith/pylith-4/lib/python3.10/site-packages/pylith/apps/PyLithApp.py", line 103, in main
    self.problem.initialize()
  File "/home/syw/pylith/pylith-4/lib/python3.10/site-packages/pylith/problems/Problem.py", line 187, in initialize
    ModuleProblem.initialize(self)
  File "/home/syw/pylith/pylith-4/lib/python3.10/site-packages/pylith/problems/problems.py", line 165, in initialize
    return _problems.Problem_initialize(self)
RuntimeError: Could not find group of points 'boundary_xneg' with label value '10' in PETSc DM mesh.
Abort(-1) on node 0 (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, -1) - process 0
/home/syw/pylith/pylith-4/bin/nemesis: mpiexec: exit 255
/home/syw/pylith/pylith-4/bin/pylith: /home/syw/pylith/pylith-4/bin/nemesis: exit 1
"""

## To Reproduce

**PETSc branch**: `[]`
**PETSc Git hash**: `[]`

**PyLith fork**: `[]`
**PyLith branch**: `[4.0.0]`
**PyLith Git hash**: `[]`

```
cd examples/box-3d
pylith step01_axialdisp.cfg
```

## Output and error message

```
 >> /home/syw/pylith/pylith-4/lib/python3.10/site-packages/pylith/apps/PyLithApp.py:77:main
 -- pylithapp(info)
 -- Running on 1 process(es).
 >> /home/syw/pylith/pylith-4/lib/python3.10/site-packages/pylith/meshio/MeshIOObj.py:38:read
 -- meshiocubit(info)
 -- Reading finite-element mesh
 >> ../../../pylith-4.0.0/libsrc/pylith/meshio/MeshIOCubit.cc:148:void pylith::meshio::MeshIOCubit::_readVertices(pylith::meshio::ExodusII&, pylith::scalar_array*, int*, int*) const
 -- meshiocubit(info)
 -- Component 'reader': Reading 2113 vertices.
 >> ../../../pylith-4.0.0/libsrc/pylith/meshio/MeshIOCubit.cc:208:void pylith::meshio::MeshIOCubit::_readCells(pylith::meshio::ExodusII&, pylith::int_array*, pylith::int_array*, int*, int*) const
 -- meshiocubit(info)
 -- Component 'reader': Reading 10049 cells in 1 blocks.
 >> ../../../pylith-4.0.0/libsrc/pylith/meshio/MeshIOCubit.cc:270:void pylith::meshio::MeshIOCubit::_readGroups(pylith::meshio::ExodusII&)
 -- meshiocubit(info)
 -- Component 'reader': Found 6 node sets.
 >> ../../../pylith-4.0.0/libsrc/pylith/meshio/MeshIOCubit.cc:296:void pylith::meshio::MeshIOCubit::_readGroups(pylith::meshio::ExodusII&)
 -- meshiocubit(info)
 -- Component 'reader': Reading node set 'boundary_xpos' with id 20 containing 140 nodes.
 >> ../../../pylith-4.0.0/libsrc/pylith/meshio/MeshIOCubit.cc:296:void pylith::meshio::MeshIOCubit::_readGroups(pylith::meshio::ExodusII&)
 -- meshiocubit(info)
 -- Component 'reader': Reading node set 'boundary_xneg' with id 21 containing 140 nodes.
 >> ../../../pylith-4.0.0/libsrc/pylith/meshio/MeshIOCubit.cc:296:void pylith::meshio::MeshIOCubit::_readGroups(pylith::meshio::ExodusII&)
 -- meshiocubit(info)
 -- Component 'reader': Reading node set 'boundary_ypos' with id 22 containing 140 nodes.
 >> ../../../pylith-4.0.0/libsrc/pylith/meshio/MeshIOCubit.cc:296:void pylith::meshio::MeshIOCubit::_readGroups(pylith::meshio::ExodusII&)
 -- meshiocubit(info)
 -- Component 'reader': Reading node set 'boundary_yneg' with id 23 containing 140 nodes.
 >> ../../../pylith-4.0.0/libsrc/pylith/meshio/MeshIOCubit.cc:296:void pylith::meshio::MeshIOCubit::_readGroups(pylith::meshio::ExodusII&)
 -- meshiocubit(info)
 -- Component 'reader': Reading node set 'boundary_zneg' with id 24 containing 185 nodes.
 >> ../../../pylith-4.0.0/libsrc/pylith/meshio/MeshIOCubit.cc:296:void pylith::meshio::MeshIOCubit::_readGroups(pylith::meshio::ExodusII&)
 -- meshiocubit(info)
 -- Component 'reader': Reading node set 'boundary_zpos' with id 25 containing 185 nodes.
 >> ../../../pylith-4.0.0/libsrc/pylith/meshio/MeshIO.cc:85:void pylith::meshio::MeshIO::read(pylith::topology::Mesh*, bool)
 -- meshiocubit(info)
 -- Component 'reader': Domain bounding box:
    (-6000, 6000)
    (-6000, 6000)
    (-9000, 0)
 >> /home/syw/pylith/pylith-4/lib/python3.10/site-packages/pylith/problems/Problem.py:116:preinitialize
 -- timedependent(info)
 -- Performing minimal initialization before verifying configuration.
 >> /home/syw/pylith/pylith-4/lib/python3.10/site-packages/pylith/problems/Solution.py:39:preinitialize
 -- solution(info)
 -- Performing minimal initialization of solution.
 >> /home/syw/pylith/pylith-4/lib/python3.10/site-packages/pylith/problems/Problem.py:174:verifyConfiguration
 -- timedependent(info)
 -- Verifying compatibility of problem configuration.
 >> /home/syw/pylith/pylith-4/lib/python3.10/site-packages/pylith/problems/Problem.py:219:_printInfo
 -- timedependent(info)
 -- Scales for nondimensionalization:
    Length scale: 1000*m
    Time scale: 3.15576e+09*s
    Pressure scale: 3e+10*m**-1*kg*s**-2
    Density scale: 2.98765e+23*m**-3*kg
    Temperature scale: 1*K
 >> /home/syw/pylith/pylith-4/lib/python3.10/site-packages/pylith/problems/Problem.py:185:initialize
 -- timedependent(info)
 -- Initializing timedependent problem with quasistatic formulation.
Fatal error. Calling MPI_Abort() to abort PyLith application.
Traceback (most recent call last):
  File "/home/syw/pylith/pylith-4/lib/python3.10/site-packages/pylith/apps/PetscApplication.py", line 55, in onComputeNodes
    self.main(*args, **kwds)
  File "/home/syw/pylith/pylith-4/lib/python3.10/site-packages/pylith/apps/PyLithApp.py", line 103, in main
    self.problem.initialize()
  File "/home/syw/pylith/pylith-4/lib/python3.10/site-packages/pylith/problems/Problem.py", line 187, in initialize
    ModuleProblem.initialize(self)
  File "/home/syw/pylith/pylith-4/lib/python3.10/site-packages/pylith/problems/problems.py", line 165, in initialize
    return _problems.Problem_initialize(self)
RuntimeError: Could not find group of points 'boundary_xneg' with label value '10' in PETSc DM mesh.
Abort(-1) on node 0 (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, -1) - process 0
/home/syw/pylith/pylith-4/bin/nemesis: mpiexec: exit 255
/home/syw/pylith/pylith-4/bin/pylith: /home/syw/pylith/pylith-4/bin/nemesis: exit 1
```

## Environment

Please provide the following information:

- OS: [Ubuntu 22.04]
- Python version: [for example Python 3.10.13]

**Comment by sheyu921** [comment]
I have solve the problem. I should comment the 'label_value' lines in 'pylithapp.cfg' and step0*.
