### ISSUE TITLE
PyLith v2.2.2: cannot adjust topology with all vertices of a cell on the fault

### ISSUE THREAD

**Issue by Ultrafollow** [geodynamics/pylith#795]
## Describe the issue
Dear sir,

I am using pylith2.2.2 to study related problems of faults and surface deformation. In the study area, I set up three faults, namely fault_main/fault_min/fault_huya. Also in the.cfg file, I set the fault placement order to parallel first and intersect (fault_min/fault_huya/fault_main).

An error was reported while calculating fault_main:''RuntimeError: Error occurred while adjusting topology to create cohesive cells for fault 'fault_main'.Ambiguous fault surface. Cell 477579 has all of its vertices on the fault.''

Please help me with this error. At the same time, I have a question, is' cell 477579 'generated after meshiocubit? Can I locate cell 477579 in the cubit gui?

Thank you.
best regards.

### .cfg
```
[pylithapp.timedependent]
interfaces = [fault_huya,fault_min,fault_main,fault_bailongjiang,fault_guanggai]
```
### .jou/.py
```
cubit.cmd("volume all scheme tetmesh")
cubit.cmd("volume all size {5*km}")
cubit.cmd("mesh volume all")
```

## Output and error message

```
Fatal error. Calling MPI_Abort() to abort PyLith application.
Traceback (most recent call last):
  File "/home/fallow/pylith-2.2.2/lib/python2.7/site-packages/pylith/apps/PetscApplication.py", line 74, in onComputeNodes
    self.main(*args, **kwds)
  File "/home/fallow/pylith-2.2.2/lib/python2.7/site-packages/pylith/apps/PyLithApp.py", line 115, in main
    mesh = self.mesher.create(self.problem.normalizer, interfaces)
  File "/home/fallow/pylith-2.2.2/lib/python2.7/site-packages/pylith/topology/MeshImporter.py", line 120, in create
    self._adjustTopology(mesh, faults)
  File "/home/fallow/pylith-2.2.2/lib/python2.7/site-packages/pylith/topology/MeshGenerator.py", line 127, in _adjustTopology
    interface.adjustTopology(mesh, firstFaultVertex, firstLagrangeVertex, firstFaultCell)
  File "/home/fallow/pylith-2.2.2/lib/python2.7/site-packages/pylith/faults/faults.py", line 344, in adjustTopology
    def adjustTopology(self, *args): return _faults.FaultCohesive_adjustTopology(self, *args)
RuntimeError: Error occurred while adjusting topology to create cohesive cells for fault 'fault_main'.
Ambiguous fault surface. Cell 477579 has all of its vertices on the fault.
application called MPI_Abort(MPI_COMM_WORLD, -1) - process 0
/home/fallow/pylith-2.2.2/bin/nemesis: mpirun: exit 255
/home/fallow/pylith-2.2.2/bin/pylith: /home/fallow/pylith-2.2.2/bin/nemesis: exit 1
```

## Screenshots
![d28fef0263eaa6b86168ddb69597291](https://github.com/user-attachments/assets/3f73d9b1-52dc-404f-af3b-140ec465f15b)

![634b4ec1b2688d5ec2d0ed8470b42e4](https://github.com/user-attachments/assets/902a1ce3-f712-4cae-bebb-325bfcc33f4b)

## Environment
- OS: Ubuntu 22.04.3 LTS
- Python version: 2.7

## Relevant data
[mesh.zip](https://github.com/user-attachments/files/18199013/mesh.zip)

**Comment by Ultrafollow** [comment]
> Based on the geometry you are showing, you should be able to generate the mesh without having all vertices of a tetrahedron on any one fault. It looks like the ordering of your faults is incorrect. You need to order them so that the main through-going fault is first followed by other faults that terminate at the main fault.
> 
> ```
> interfaces = [fault_main, fault_min, fault_huya, fault_guangai, fault_bailongjiang]
> ```
> 
> PyLith and PETSc, the numbering is different. All entities (vertices, edges, faces, and cells) use a single numbering. Additionally, if the mesh reordering is turned on, the mesh is reordered to optimize the memory layout.

Thank you for your reply. I've tried it in this order before. The program reports the following error:
```
RuntimeError: Error occurred while adjusting topology to create cohesive cells for fault 'fault_min'.
Error in topology of mesh associated with symmetry of adjacency information.
application called MPI_Abort(MPI_COMM_WORLD, -1) - process 0
/home/fallow/pylith-2.2.2/bin/nemesis: mpirun: exit 255
/home/fallow/pylith-2.2.2/bin/pylith: /home/fallow/pylith-2.2.2/bin/nemesis: exit 1
```

**Comment by baagaard-usgs** [comment]
I would back up and start with just the main fault, then just 'fault_min', and then the main fault while adding one fault at a time. It looked like you have the buried edges marked correctly, but I may have missed something. Make sure the vertices at the intersection are in the "buried edges" for the fault that terminates at the intersection.You can check the fault surface in the PyLith output for each case with just a single fault to make sure the topology matches what you expect and you don't have anything odd around the edges of the faults.

**Comment by Ultrafollow** [comment]
> I would back up and start with just the main fault, then just 'fault_min', and then the main fault while adding one fault at a time. It looked like you have the buried edges marked correctly, but I may have missed something. Make sure the vertices at the intersection are in the "buried edges" for the fault that terminates at the intersection.You can check the fault surface in the PyLith output for each case with just a single fault to make sure the topology matches what you expect and you don't have anything odd around the edges of the faults.

Thank you for your reply.
Following your advice, I found that I did not specify the label "buried edges" in the.cfg file during the attempt. After I specify, the solution domain model made of tetrahedrons no longer reports errors. It should be pointed out that the order you think is correct:
```
interfaces = [fault_main, fault_min, fault_huya, fault_guanggai, fault_bailongjiang]
```
During the program's operation, there were errors reported where the number of degrees of freedom (DOF) for boundary conditions exceeded three. After I removed the overlap in the boundary nodeset, the error disappeared. Now a new error message appears.How can I fix this error?Kindly advice. Thank you.
```
500 SNES Function norm 4.576757430800e-06 
Nonlinear solve did not converge due to DIVERGED_MAX_IT iterations 500
[0]PETSC ERROR: --------------------- Error Message --------------------------------------------------------------
[0]PETSC ERROR:   
[0]PETSC ERROR: SNESSolve has not converged
[0]PETSC ERROR: See http://www.mcs.anl.gov/petsc/documentation/faq.html for trouble shooting.
[0]PETSC ERROR: Petsc Release Version 3.10.2, Jul, 01, 2019 
[0]PETSC ERROR: /home/fallow/pylith-2.2.2/bin/mpinemesis on a  named fallow-virtual-machine by fallow Sat Dec 21 15:44:46 2024
[0]PETSC ERROR: Configure options --prefix=/home/brad/pylith-binary/dist --with-c2html=0 --with-x=0 --with-clanguage=C --with-mpicompilers=1 --with-shared-libraries=1 --with-64-bit-points=1 --with-large-file-io=1 --download-chaco=1 --download-ml=1 --download-f2cblaslapack=1 --with-hwloc=0 --with-ssl=0 --with-x=0 --with-c2html=0 --with-lgrind=0 --with-hdf5=1 --with-hdf5-dir=/home/brad/pylith-binary/dist --with-zlib=1 --LIBS=-lz --with-debugging=0 --with-fc=0 CPPFLAGS="-I/home/brad/pylith-binary/dist/include -I/home/brad/pylith-binary/dist/include " LDFLAGS="-L/home/brad/pylith-binary/dist/lib -L/home/brad/pylith-binary/dist/lib64 -L/home/brad/pylith-binary/dist/lib -L/home/brad/pylith-binary/dist/lib64 " CFLAGS="-g -O2" CXXFLAGS="-g -O2 -DMPICH_IGNORE_CXX_SEEK" FCFLAGS= PETSC_DIR=/home/brad/pylith-binary/build/petsc-pylith PETSC_ARCH=arch-pylith
[0]PETSC ERROR: #1 SNESSolve() line 4408 in /home/brad/pylith-binary/build/petsc-pylith/src/snes/interface/snes.c
[0]PETSC ERROR: #2 void pylith::problems::SolverNonlinear::solve(pylith::topology::Field*, pylith::topology::Jacobian*, const pylith::topology::Field&)() line 152 in ../../../pylith-2.2.2/libsrc/pylith/problems/SolverNonlinear.cc
Fatal error. Calling MPI_Abort() to abort PyLith application.
Traceback (most recent call last):
  File "/home/fallow/pylith-2.2.2/lib/python2.7/site-packages/pylith/apps/PetscApplication.py", line 74, in onComputeNodes
    self.main(*args, **kwds)
  File "/home/fallow/pylith-2.2.2/lib/python2.7/site-packages/pylith/apps/PyLithApp.py", line 138, in main
    self.problem.run(self)
  File "/home/fallow/pylith-2.2.2/lib/python2.7/site-packages/pylith/problems/TimeDependent.py", line 203, in run
    self.formulation.step(t, dt)
  File "/home/fallow/pylith-2.2.2/lib/python2.7/site-packages/pylith/problems/Implicit.py", line 212, in step
    self.solver.solve(dispIncr, self.jacobian, residual)
  File "/home/fallow/pylith-2.2.2/lib/python2.7/site-packages/pylith/problems/problems.py", line 186, in solve
    def solve(self, *args): return _problems.SolverNonlinear_solve(self, *args)
RuntimeError: Error detected while in PETSc function.
application called MPI_Abort(MPI_COMM_WORLD, -1) - process 0
/home/fallow/pylith-2.2.2/bin/nemesis: mpirun: exit 255
/home/fallow/pylith-2.2.2/bin/pylith: /home/fallow/pylith-2.2.2/bin/nemesis: exit 1
```
Here are my Settings:
```
# ----------------------------------------------------------------------
# PETSc
# ----------------------------------------------------------------------
# Set the solver options.
[pylithapp.petsc]
malloc_dump =
pc_type = asm
sub_pc_factor_shift_type = nonzero
ksp_rtol = 1.0e-20
ksp_atol = 1.0e-12
ksp_max_it = 500
ksp_gmres_restart = 50
ksp_monitor = true
ksp_view = true
ksp_converged_reason = true
ksp_error_if_not_converged = true
snes_rtol = 1.0e-20
snes_atol = 1.0e-9
snes_max_it = 500
snes_monitor = true
snes_linesearch_monitor = true
snes_converged_reason = true
snes_error_if_not_converged = true
log_view = true
```
and faults settings:
```
[pylithapp.timedependent.interfaces.fault_main]
zero_tolerance = 1.0e-8
zero_tolerance_normal = 1.0e-6
label = fault_main
id = 20
edge = fault_main_edges
friction = pylith.friction.StaticFriction
friction.label = Static friction
quadrature.cell = pylith.feassemble.FIATSimplex
quadrature.cell.dimension = 2
friction.db_properties = spatialdata.spatialdb.UniformDB
friction.db_properties.label = Static friction
friction.db_properties.values = [friction-coefficient,cohesion]
friction.db_properties.data = [0.6,2.0*MPa]
```
Here is my model:
![image](https://github.com/user-attachments/assets/573483c4-06e7-43b8-9e91-217ce0341564)

**Comment by Ultrafollow** [comment]
Hello @knepley and @baagaard-usgs.Thank you for your advice.I have temporarily solved the Error of "Error occurred while adjusting topology to create cohesive cells". But a new error about "Nonlinear solve did not converge" appeared.
```
3332 SNES Function norm 4.580204851900e-06 
Nonlinear solve did not converge due to DIVERGED_FUNCTION_COUNT iterations 3332
[0]PETSC ERROR: --------------------- Error Message --------------------------------------------------------------
[0]PETSC ERROR:   
[0]PETSC ERROR: SNESSolve has not converged
[0]PETSC ERROR: See http://www.mcs.anl.gov/petsc/documentation/faq.html for trouble shooting.
[0]PETSC ERROR: Petsc Release Version 3.10.2, Jul, 01, 2019 
[0]PETSC ERROR: /home/fallow/pylith-2.2.2/bin/mpinemesis on a  named fallow-virtual-machine by fallow Sun Dec 22 04:01:39 2024
[0]PETSC ERROR: Configure options --prefix=/home/brad/pylith-binary/dist --with-c2html=0 --with-x=0 --with-clanguage=C --with-mpicompilers=1 --with-shared-libraries=1 --with-64-bit-points=1 --with-large-file-io=1 --download-chaco=1 --download-ml=1 --download-f2cblaslapack=1 --with-hwloc=0 --with-ssl=0 --with-x=0 --with-c2html=0 --with-lgrind=0 --with-hdf5=1 --with-hdf5-dir=/home/brad/pylith-binary/dist --with-zlib=1 --LIBS=-lz --with-debugging=0 --with-fc=0 CPPFLAGS="-I/home/brad/pylith-binary/dist/include -I/home/brad/pylith-binary/dist/include " LDFLAGS="-L/home/brad/pylith-binary/dist/lib -L/home/brad/pylith-binary/dist/lib64 -L/home/brad/pylith-binary/dist/lib -L/home/brad/pylith-binary/dist/lib64 " CFLAGS="-g -O2" CXXFLAGS="-g -O2 -DMPICH_IGNORE_CXX_SEEK" FCFLAGS= PETSC_DIR=/home/brad/pylith-binary/build/petsc-pylith PETSC_ARCH=arch-pylith
[0]PETSC ERROR: #1 SNESSolve() line 4408 in /home/brad/pylith-binary/build/petsc-pylith/src/snes/interface/snes.c
[0]PETSC ERROR: #2 void pylith::problems::SolverNonlinear::solve(pylith::topology::Field*, pylith::topology::Jacobian*, const pylith::topology::Field&)() line 152 in ../../../pylith-2.2.2/libsrc/pylith/problems/SolverNonlinear.cc
Fatal error. Calling MPI_Abort() to abort PyLith application.
Traceback (most recent call last):
  File "/home/fallow/pylith-2.2.2/lib/python2.7/site-packages/pylith/apps/PetscApplication.py", line 74, in onComputeNodes
    self.main(*args, **kwds)
  File "/home/fallow/pylith-2.2.2/lib/python2.7/site-packages/pylith/apps/PyLithApp.py", line 138, in main
    self.problem.run(self)
  File "/home/fallow/pylith-2.2.2/lib/python2.7/site-packages/pylith/problems/TimeDependent.py", line 203, in run
    self.formulation.step(t, dt)
  File "/home/fallow/pylith-2.2.2/lib/python2.7/site-packages/pylith/problems/Implicit.py", line 212, in step
    self.solver.solve(dispIncr, self.jacobian, residual)
  File "/home/fallow/pylith-2.2.2/lib/python2.7/site-packages/pylith/problems/problems.py", line 186, in solve
    def solve(self, *args): return _problems.SolverNonlinear_solve(self, *args)
RuntimeError: Error detected while in PETSc function.
application called MPI_Abort(MPI_COMM_WORLD, -1) - process 0
/home/fallow/pylith-2.2.2/bin/nemesis: mpirun: exit 255
/home/fallow/pylith-2.2.2/bin/pylith: /home/fallow/pylith-2.2.2/bin/nemesis: exit 1
```
In order to solve the non-convergence error, I increased the number of iterations from 500 to 10,000, and modified the parameters of PETSc. However, a non-converging error still appears, this time indicating "3332 SNES Function norm 4.580204851900e-06.Nonlinear solve did not converge due to DIVERGED_FUNCTION_COUNT iterations 3332 ". 
May I ask why I set 10000 iterations, but it does not converge when the sequence number 3332.I will attach the relevant configuration file at the end of the message. How long does a simulation like this take to run on a laptop?Thank you again for everything you've done.
[cfgFile.zip](https://github.com/user-attachments/files/18220978/cfgFile.zip)
